//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 01:40:07 PM CEST 
//


package com.gestor.sms.catastro.provincias;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.catastro.meh.es/}control"/>
 *         &lt;element ref="{http://www.catastro.meh.es/}provinciero"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "control",
    "provinciero"
})
@XmlRootElement(name = "consulta_provinciero")
public class ConsultaProvinciero {

    @XmlElement(required = true)
    protected Control control;
    @XmlElement(required = true)
    protected Provinciero provinciero;

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link Control }
     *     
     */
    public Control getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link Control }
     *     
     */
    public void setControl(Control value) {
        this.control = value;
    }

    /**
     * Gets the value of the provinciero property.
     * 
     * @return
     *     possible object is
     *     {@link Provinciero }
     *     
     */
    public Provinciero getProvinciero() {
        return provinciero;
    }

    /**
     * Sets the value of the provinciero property.
     * 
     * @param value
     *     allowed object is
     *     {@link Provinciero }
     *     
     */
    public void setProvinciero(Provinciero value) {
        this.provinciero = value;
    }

}
