//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 01:40:07 PM CEST 
//


package com.gestor.sms.catastro.provincias;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gestor.sms.catastro.provincias package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gestor.sms.catastro.provincias
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link Provinciero }
     * 
     */
    public Provinciero createProvinciero() {
        return new Provinciero();
    }

    /**
     * Create an instance of {@link ConsultaProvinciero }
     * 
     */
    public ConsultaProvinciero createConsultaProvinciero() {
        return new ConsultaProvinciero();
    }

    /**
     * Create an instance of {@link Prov }
     * 
     */
    public Prov createProv() {
        return new Prov();
    }

}
